# Teil 1: Optionen
include_dateien    = [    # wo wird nach .h Dateien gesucht?
    '.'                   # im lokalen Verzeichnis
]
shared_libraries   = [
   'm'                    # mathematische Funktionen der Standardbibliothek
]
cpp_standard       = [    # Angaben zum Standard
    '-std=c++98',         # ISO/IEC Standard 14882
    '-pedantic'           # keine Erweiterungen zulaessig
]
warnungen          = [    # Einstellungen zu Fehlern
    '-Wall',              # viel meckern
    '-Wextra',            # extra viel meckern
    '-Werror'             # Warnungen sind Fehler
]
# Teil 2: Definition des Environments
std = Environment(
  CXXFLAGS = cpp_standard + warnungen,
  CPPPATH = include_dateien,
  LIBS     = shared_libraries
)
# Teil 3: Programm bauen
cpp_dateien = [                     # hier C++-Dateien einfuegen
    'main.cpp',        				# Kommentar moeglich
    'libs/Anschrift.cpp',           # Kommentar moeglich
    'libs/Datum.cpp',           	# Kommentar moeglich
    'libs/Dienstzimmer.cpp',      	# Kommentar moeglich
    'libs/Mitarbeiter.cpp',      	# Kommentar moeglich
    'libs/Email.cpp',              	# Kommentar moeglich
    'libs/mein_zufall.cpp',        	# Kommentar moeglich
    'libs/Name.cpp',         		# Kommentar moeglich
    'libs/Ort.cpp',         		# Kommentar moeglich
    'libs/Person.cpp',         		# Kommentar moeglich
    'libs/Professor.cpp',         		# Kommentar moeglich
    'libs/Student.cpp',         	# Kommentar moeglich
    'libs/Telefon.cpp',         	# Kommentar moeglich
    'libs/Fachbereich.cpp',         	# Kommentar moeglich
    'libs/Studiengang.cpp',         	# Kommentar moeglich
    'libs/Sprechstunde.cpp',         	# Kommentar moeglich
    'libs/Uhrzeit.cpp',         	# Kommentar moeglich
    'libs/Wochentag.cpp',         	# Kommentar moeglich
    'libs/ausgabe.cpp',         	# Kommentar moeglich
    'libs/eingabe.cpp',         	# Kommentar moeglich
]
programm_name = 'Personenverwaltung'   # hier Programmnamen festlegen
std.Program(programm_name, cpp_dateien) # Programm bauen

