# Teil 1: Optionen
include_dateien    = [    # wo wird nach .h Dateien gesucht?
    '.'                   # im lokalen Verzeichnis
]
shared_libraries   = [
   'm'                    # mathematische Funktionen der Standardbibliothek
]
cpp_standard       = [    # Angaben zum Standard
    '-std=c++98',         # ISO/IEC Standard 14882
    '-pedantic'           # keine Erweiterungen zulaessig
]
warnungen          = [    # Einstellungen zu Fehlern
    '-Wall',              # viel meckern
    '-Wextra',            # extra viel meckern
    '-Werror'             # Warnungen sind Fehler
]
# Teil 2: Definition des Environments
std = Environment(
  CXXFLAGS = cpp_standard + warnungen,
  CPPPATH = include_dateien,
  LIBS     = shared_libraries
)
# Teil 3: Programm bauen
cpp_dateien = [                         # hier C++-Dateien einfuegen
    'fliegen_main.cpp',        # Kommentar moeglich
    'libs/Flug.cpp',            # Kommentar moeglich
    'libs/Flughafen.cpp',            # Kommentar moeglich
    'libs/Flugtag.cpp',       # Kommentar moeglich
    'libs/Flugzeug.cpp',              # Kommentar moeglich
    'libs/mein_zufall.cpp',         # Kommentar moeglich
    'libs/eingabe.cpp',         # Kommentar moeglich
    'libs/ausgabe.cpp',         # Kommentar moeglich
]
programm_name = 'Fahrkarte_bitte'               # hier Programmnamen festlegen
std.Program(programm_name, cpp_dateien) # Programm bauen

